katcp/client.py
katcp/ioloop_manager.py
katcp/resource_client.py
katcp/server.py

Useful, since recent versions of Python don't run atexit handlers
before all non-daemon threads have stopped. This means you can't use
atexit for automatic thread-stopping in interactive use unless your ioloop thread is daemonic.
See Alex Martelli's answer (and comment by Neilen Marais)
http://stackoverflow.com/questions/2564137/python-how-to-terminate-a-thread-when-main-program-ends
and answer to
http://stackoverflow.com/questions/3713360/python-2-6-x-theading-signals-atexit-fail-on-some-versions

Add option to daemonize ioloop_manager thread

---

katcp/core.py
katcp/fake_clients.py
katcp/inspecting_client.py
katcp/kattypes.py
katcp/resource_client.py
katcp/test/test_fake_clients.py
katcp/test/test_inspectclient.py
katcp/test/test_kattypes.py
katcp/test/test_resource_client.py

Functionality for clients that fake server connections on the client side. Useful for testing, and hopefully useful for kattelmod's time-warping telescope simulation, since all clients share the same ioloop allowing ioloop time-warp tricks to be used. Allows clients at the level op InspectingClient, KATCPClientResource and KATCPClientResourceContainer to be faked, with the ability for request-handlers and sensors to be installed on the 'fake' server.
@ludwigschwardt  FYI

Fake resource support

---

katcp/inspecting_client.py
katcp/resource.py
katcp/resource_client.py
katcp/test/test_resource_client.py
katcp/testutils.py

Allows strategies for sensors of interest to be set before they have appeared
(e.g. at app startup before the client has had a chance to sync, or if a dynamic
device has not made a given sensor available yet)

Add ability to pre-set sensor strategies in KATCPResource.

---

katcp/resource_client.py
katcp/test/test_resource_client.py

Makes it easier for collaborating classes to be sure to use the correct ioloop.

Store ioloop as KATCPClientResourceContainer attribute

---

katcp/resource_client.py

@lvdheever / @profcalculus 
Allow for wrapping of attributes of type `resource.ClientGroup` (i.e. to ensure the group requests are blocking when wrapped)

Allow for wrapping of attributes of type `resource.ClientGroup`

---

katcp/ioloop_manager.py
katcp/server.py

By returning a future that resolves when the server shutdown cleanup code has
completed, ioloop.run_sync(device.stop) can be used to cleanly shut down a KATCP
server (including sending of disconnect messages) after catching a
KeyboardInterrupt when the ioloop is run in the main thread. E.g. something
like:
```py
...
server = katcp.DeviceSever(....)
ioloop.add_callback(server.start)
try:
ioloop.start()
except KeyboardInterrupt:
ioloop.run_sync(server.stop)
```

DeviceServer.stop() now returns a future

---

doc/tutorial.rst
katcp/ioloop_manager.py

Also updated documentation with an async server example. The suggestion in the
previous commit was wrong, since ioloop.run_sync() does nor work properly if an
ioloop was ended by a KeyboardInterrupt. Here is a properly working example:
```py
@tornado.gen.coroutine
def on_shutdown(ioloop, server):
print('Shutting down')
yield server.stop()
ioloop.stop()
if __name__ == "__main__":
ioloop = tornado.ioloop.IOLoop.current()
server = MyServer(server_host, server_port)
server.set_concurrency_options(thread_safe=False, handler_thread=False)
server.set_ioloop(ioloop)
signal.signal(signal.SIGINT, lambda sig, frame: ioloop.add_callback_from_signal(
on_shutdown, ioloop, server))
ioloop.add_callback(server.start)
ioloop.start()
```

Fix IOLoopManager.stop() to actually return a future

---

katcp/testutils.py

WaitingMock.reset_mock() could fail when invoked from mock.Mock()

Changed reset_mock() signature to match base class

---

katcp/resource_client.py

The timeout parameter on the decorator itself is never used. Rather get rid
of it and extract the relevant timeout from the kwargs of the original request.
This way the user can override timeouts per request (as opposed to per ioloop
wrapper).
A future improvement might be to make the ioloop timeout slightly longer than
the request timeout to allow the request to drive the error reporting to the
user.
@brickZA to have a look as well.

Use request timeout in ioloop wrapper

---

katcp/resource.py

Exposes parse_value from the _sensor on the katcp resource.
This is required for use as a replacement for the old format_type method.
please review and merge.

exposed parse value on katcp resource

---

katcp/core.py
katcp/resource.py
katcp/resource_client.py
katcp/test/test_resource_client.py

@martinslabber @profcalculus Please have a look.
This implements the neccesary client side functionality to allow 'dummy-requests' to be done.  Next move would be modifying katsubarray to add the 'dummy_unknown_requests' flag to the resource client configuration dicts as appropriate.

Add a client-side dummy-request facility CB-918

---

katcp/resource_client.py
katcp/test/test_resource_client.py

This allows the dynamic addition of client groups on the container.
It does this by inserting the new group into the resource spec and updating
the groups property, which allows the higher-level thread-safe container
to wrap the new group properly.
There is no real need to remove groups as they are innocuous if they hang
around.

New add_group method on container

---

katcp/resource_client.py
katcp/test/test_resource_client.py

ClientGroups have req objects and therefore also qualify for dummy
unknown requests. Since a group is not constructed from resource specs,
provide dummy requests if any of its underlying clients have them.

Add dummy unknown requests to ClientGroups

---

katcp/client.py
katcp/ioloop_manager.py

When the python interpreter exits it garbage collects all generators that still
exists. Sometimes (usually in tests when the test classes keep references to
everything) tornado coroutines (which are generators) might still exist in a
limbo state after the ioloop on which they were running has stopped. The client
has a finally statement in its main coroutine that tries to shutdown
cleanly. This does not work well when the ioloop has been stopped, and ends up
blocking the python interepreter exit for a second or so. Multiply by the number
of clients, this can be quite long at the end of a test run
By simply using add_callback to run the cleanup, nothing bad happens if the
ioloop is no longer running.

Avoid blocking python interpreter shutdown and avoid leaking file descriptors CB-1146

---

katcp/inspecting_client.py
katcp/resource_client.py
katcp/test/test_resource_client.py

Allow high level clients to preset KATCP flags, allows broken servers

---

katcp/resource.py
katcp/resource_client.py
katcp/test/test_resource.py
katcp/test/test_resource_client.py

The current wait() machinery is unsatisfactory. If the sensor
meets the condition, wait() returns True. On the other hand,
if the sensor does not meet the condition before the timeout,
a TimeoutError is raised. Wait() never returns False, making
the whole thing quite asymmetric.
The TimeoutErrors currently cause observation scripts to
crash (mostly for no good reason). Catching the exception
within the observation framework is messy.
My proposal is to swallow the TimeoutError at the KATCPResource
level and turn it into a proper symmetric False return.
User-facing client and client group objects will therefore
never crash like this again.
In addition, the ClientGroup.wait now returns extra information
that allows the user to report back on which clients have failed
the sensor condition …

Simplify sensor wait() interface

---

katcp/inspecting_client.py

removed __del__ method that calls the join on katcp_client (which in turn calls join on the io_loop_manager's thread join) because it was causing a massive memory leak for anyone using the KATCPClientResourceContainer

CB-1320 - plug memory leak in KATCPClientResourceContainer

---

katcp/server.py

With this change the log method is a bit more robust. We see log messages with the "%s" string in them, an upstream error. These log messages causes KATCP to throw a stack trace and in the process shadow the real error.
I wonder if we should cleanup the log message, or alert the user that it was malformed.
e.g. Maybe this would be better. What do you think?
```
inform_msg = "(malformed log message) {} {}".format(
msg.replace("%s", "?"),
args if args else '').strip(' ?')
```

Handle malformed log lines.

---

katcp/client.py
katcp/core.py
katcp/inspecting_client.py
katcp/resource_client.py
katcp/test/test_inspectclient.py
katcp/testutils.py

On the dev32 system the single process that is trying to connect and sync to all 32
dishes takes too long, resulting in some of the inspection requests timing
out. InspectingClient was ignoring these errors, resulting in a client that says
it is synced, but does not properly reflect its server's state
Also added a random-exponential retry backoff process to ensure that the
thundering herd does not continue thundering

Properly handle errors during inspection in inspecting client

---

katcp/inspecting_client.py
katcp/resource_client.py
katcp/test/test_inspectclient.py

When sensor sync failed, requests model updates were never sent by inspecting
client callback

CB-1591 fix partial sync failure case

---

katcp/resource_client.py

Catching it there serves no purpose. The only way that
`future.result(timeout)` can raise a KeyboardInterrupt is if the main
thread is waiting on a future running on the ioloop in another thread.
If SIGINT is received, the KeyboardInterrupt should indeed propagate.

Remove spurious KeyboardInterrupt catch in IOLoopThreadWrapper

---

katcp/test/test_testutils.py
katcp/testutils.py

Occasionally there were unexpected failures in another repo with tests using `assert_called_once_with()`, directly after `assert_wait_call_count()`.  The particular tests that were failing were testing requests which started a new thread, and then raised `AsyncReply`.  When the thread completed, it would send the actual reply.
The issue was returning too early from `assert_wait_call_count`, before the mock object's `call_args_list` has been updated.

Improve WaitingMock.assert_wait_call_count

---

katcp/core.py
katcp/kattypes.py
katcp/server.py
katcp/test/test_core.py
katcp/test/test_server.py
katcp/testutils.py

Idea is that we want a server to explicitly tell a client that it can use the ?request-timeout-hint request without the client having to guess.

Add timeout hint protocol flag CB-569

---

katcp/inspecting_client.py
katcp/resource.py
katcp/resource_client.py
katcp/server.py
katcp/test/test_inspecting_client.py
katcp/test/test_resource.py
katcp/test/test_resource_client.py
katcp/testutils.py

This is an evil idea we hatched at CAM to enable devices to tell clients which requests are likely to be slow. Still experimenting, but if it looks nice we might try and propose it as a KATCP v5.1 protocol feature :)

Let resource client use timeout hints

---

katcp/core.py
katcp/resource_client.py
katcp/test/test_core.py
katcp/test/test_resource_client.py

Give ```ClientGroup.wait()``` the ability to wait until a subset of clients (a 'quorum') satisfy a sensor condition. This provides a way to e.g. ignore a broken or stowed receptor while slewing the working receptors onto a target. The wait times out if a quorum could not be achieved in the given timeout period. The desired quorum can be specified as either a number or a fraction of clients.
An additional grace period, which forms part of the overall timeout, allows for some fine-tuning of the behaviour. All remaining clients that have not yet satisfied the condition (the 'stragglers') are given the opportunity to do so within the grace period. This can effectively result in a full quorum by the time the wait resolves, if all clients behave as expected.
The default behaviour is unchanged: …

Let ClientGroup wait for a quorum of clients

---

katcp/__init__.py
katcp/client.py
katcp/core.py
katcp/fake_clients.py
katcp/inspecting_client.py
katcp/ioloop_manager.py
katcp/kattypes.py
katcp/object_proxies.py
katcp/resource.py
katcp/resource_client.py
katcp/sampling.py
katcp/sensortree.py
katcp/server.py
katcp/test/test_client.py
katcp/test/test_core.py
katcp/test/test_fake_clients.py
katcp/test/test_inspecting_client.py
katcp/test/test_ioloop_manager.py
katcp/test/test_katcp_bnf.py
katcp/test/test_kattypes.py
katcp/test/test_resource.py
katcp/test/test_resource_client.py
katcp/test/test_sampling.py
katcp/test/test_sensortree.py
katcp/test/test_server.py
katcp/test/test_testutils.py
katcp/testutils.py
setup.py

Futurize a small part of KATCP lib as a proof of concept. Also got rid of the python 2 ProxyTypes dependency by moving it into our codebase (only about 200 lines) and also making it python 2/3 compatible.
Going forward, files that have been marked with `# Python 2/3 compatibility stuff` comment near the top should use python 2/3 compatible idioms: http://python-future.org/compatible_idioms.html

User/nmarais/ci 27/initial futurize work for python 2/3 compatibility

---

setup.py

This is necessary because the `tornado.gen.Multi` class and the function
`multi_future` was replaced with a unified function `multi` in 4.3. We
use `multi` since df82a33252a1d6196646b4a267cbf9583301f919 (didn't check
earlier commits)

Bumped tornado dependency to 4.3 in setup.py

---

katcp/inspecting_client.py

just aggrevated the situation of multiple clients connecting at the same time.
Tested on dev64 and cam.status() for the full 64-dish container settles nicely within ~5s after configure_cam() without a myriad of error messages.

Increase container sync time as the 8s timeout with 1s kickoff 

---

katcp/resource.py
katcp/resource_client.py
katcp/test/test_resource.py
katcp/test/test_resource_client.py

When using a `KATCPClientResource`, once a sampling strategy has been set it gets cached and there is no way to remove it.  It can be set to 'none', but after disconnect/sync events there
will still be attempts to apply it.  This can cause unnecessary errors and exceptions to be logged when many sensors that were being sampled are removed from the server's KATCP interface.  The
errors occur during `reapply_sampling_strategies`.  It might be possible to fix the errors by changing something in the sync process, but not sure.
The workaround is to provide a mechanism to drop cached sensor strategies on demand.  This is now available as `drop_sampling_strategy`.
JIRA: [CB-2544](https://skaafrica.atlassian.net/browse/CB-2544)

Allow sampling strategy to be removed from cache

---

katcp/core.py

Providing meaningful error messages for when the asserts fail.

A descriptive error message for the DeviceMetaClass assert statements

---

katcp/server.py

Increase in queue size to cater for more concurrent client connections.  One of our processes has around 90 clients.
This was hotfixed in a release branch, PR #199, about a year ago.  Forgot to add to to master.
Ideally the limit should be a function of the number of connected clients, but that is more effort to implement.  Note that the limit used to be just 3, assuming a single client - this was changed in 6aabfb8bd1e to allow for "multiple" clients.
JIRA: [MT-92](https://skaafrica.atlassian.net/browse/MT-92)

Increase MAX_QUEUE_SIZE to handle more clients

---

LICENSE
doc/conf.py
katcp/fake_clients.py

Renamed license header from *SKA South Africa* to *National Research Foundation (South African Radio Astronomy Observatory)*, which is consistent across most of the files.

Updated license header on files.

---

tox.ini

This PR does the following:
- Removes pip index and trusted hosts related information from `tox.ini` file.

Removed pip's index and trusted hosts

---

katcp/core.py
katcp/server.py

The `@var` comments are duplicates of the description in the class docstrings, and sometimes provide inaccurate information, so removing them.  Also some further improvements to the `Server` class docstring to try to make the usage clearer.
Issue: #229

Improve Sensor, Message and Server class docstrings 

---

tox.ini

This PR does the following:
- Pins testing dependencies due to the latest version of Mock causes python3.xx tests to fail: http://ci.camlab.kat.ac.za/job/katcp-multibranch/job/master/31/console

Pinned mock and coverage dependencies.

---

katcp/kattypes.py
katcp/test/test_kattypes.py

This PR does the following:
This fixes: https://github.com/ska-sa/katcore/blob/4db3ec97d140ba4917be68d2335660e7f06baa1d/katcore/sim_base.py#L161
JIRA: [MT-1543](https://skaafrica.atlassian.net/browse/MT-1543)

Support for handling generator expressions in Discrete type

---

katcp/test/test_server.py
katcp/testutils.py

This PR adds a test and functionality that allows bytes and strings to work with `test_sensor_list`.

allow bytes and strings in test sensor list comparison of sensors.

---

katcp/test/test_server.py

this PR aligns `test_server.py` with black formatting  see https://github.com/ska-sa/katcp-python/pull/245#discussion_r479337508
please note that PR illustrates the use of black autoformat and the conflicts our internal CI and its linter. Please provide comments and suggestions directed to fixing this through configuring black and not issues that are presented in the CI through its linting.

ran black on test_server

---

katcp/test/test_server.py
katcp/testutils.py

This PR corrects the handling of floats in the`sensor_tuple` helper function used in `test_sensor_list`.
- This adds a new float sensor with a zero to the right of the decimal point 
- Tests where the sensor is tested correctly inside `test_sensor_list`

Correct handling of floats test sensor list

---

doc/releasenotes.rst

Some notes were missing for v0.7.0, v0.7.1 and for v0.7.2

Add missing release notes

---

doc/how_to_contribute.rst

Updating the `Upload the new version to PyPI` section on [readthedocs](https://katcp-python.readthedocs.io/en/v0.8.0/how_to_contribute.html#releasing-a-new-version)

Update instructions on readthedocs for releasing a new version

---

CHANGELOG.md
doc/releasenotes.rst
katcp/resource.py
katcp/test/test_resource.py

This PR addresses issues in `KATCPReply` and its `__repr__` method.
`katcp.Message`  arguments are returned as bytes in python 3 this causes issues in `KATCPReply` `__repr__` method using the `katcp.compat.ensure_native_str` fixes this.

Fixes issues with katcpreply repr in py3

---

katcp/kattypes.py

This ensures that the error in Py2 and Py3 is consistent as the value is a `str`.
This is required for tests in other packages that rely on katcp-python and test katcp devices and failed responses.

consistent error message in py2 and py3 for error in Timestamp decode
