ska-sa/katcp-python

- katcp/core.py
- katcp/inspecting_client.py
- katcp/test/test_inspectclient.py
@brickZA: to merge ... Added initial_state to AsyncState and explicitly set initial state of InspectingClient to InspectingClientStateType with all attributes False
> Added initial_state to AsyncState and explicitly set initial state of InspectingClient

- katcp/kattypes.py
> Improve @request decorator error message for mis-named methods

- katcp/resource.py
- katcp/test/test_resource.py
Also implement KATCPResource.wait() in usingKATCPSensor.wait()
> Add basic KATCPSensensor.wait()

- katcp/core.py
> Add docstring in response to PR75 comment

- katcp/server.py
> Fixing log-level requests

- katcp/server.py
@ofaletse please review and merge
> Fixing log level in katcp that causes breaks in katcore

- katcp/server.py
Reverts ska-sa/katcp-python#83
Need a bit more work.
> Revert "Fixing log level in katcp that causes breaks in katcore"

- katcp/server.py
@martinslabber please can you review and merge.
- OFF is the highest possible logging level and is intended to turn logging off.
No information. Devices should never log messages directly to the OFF logging level.
> Add off level

- katcp/client.py
- katcp/resource_client.py
Added is_connected for backwards compatibility 
and changed "Failed to connect" log from warn to debug
> Lize add is connected

- katcp/resource.py
This was needed for backwards compatibility and to contain the further ripple of now using KATCPResource.
@profcalculus : Please review and merge
> Rework listener

- katcp/resource.py
- katcp/resource_client.py
@lvdheever / @profcalculus 
Added missing `ClientGroup` methods:
- is_connected
- set_sensor_strategies
Tested in ipython session to be ok (not yet through unit tests).
> Add missing clientgroup methods

- katcp/resource.py
- katcp/resource_client.py
@theunsa: The final change to get aggregates to work was a typo in comparing the item_name
> Rework aggregates

- katcp/resource_client.py
This may still be problematic for mon_xxx sensors as we would not be able to determine the parent of the agg_ sensor.
> Handle case when sensor is not yet available better

- katcp/resource.py
- katcp/resource_client.py
Kataware alarms now processed correctly.
> Rework for alarms

- katcp/resource.py
> Bugfix listener footprint when reading is used

- katcp/resource.py
> added a yield for the future that list_sensors now returns

- katcp/resource_client.py
Add parent class so that it can be used to determine the prefix.
Parent_class KATCPResourceClientContainer will add "comp." prefix to name returned (except for aggs)
> Update list sensors

- katcp/resource.py
- katcp/resource_client.py
…esource.wait; Also implemented wait for ClientGroup.
> Fix resource waits

- katcp/resource.py
- katcp/resource_client.py
Fix internal register_listeners to use reading=True
> Lize resource rework

- katcp/resource_client.py
@theunsa or @lvdheever 
Please review and merge.
> Add resource client to resource container

- katcp/client.py
> Fix bracket typo in exception message formatting

- katcp/test/test_resource_client.py
Some more test fixes. 2 more to go.
> Lize update tests

- katcp/inspecting_client.py
It seem the sensor-management code is somehow leaking memory. However, once a
sensor has been instantiated there is no real need to use that machinery on
every update. As a temporary workaround a sensor object cache is added. If the
sensor is not found the original process is followed. This should result in
memory only being leaked when a sensor has changed or is newly added, not on
every sensor update.
Not sure while it is leaking (will still investigate), but this should 99.99%
solve the problem :)
When reviewing please check very carefully if there won't be a problem with the
object cache in the case were sensors are removed or updated. We might as well keep this cache around since it should considerably speed up the common-case of an already-instantiated sensor update being received. …
> Add sensor object cache to InspectingClient CM-593

- katcp/core.py
Should also help with CM-593.
The implemented solution depends on the internals of tornado.concurrent.Future,
so won't work with thread-safe futures. Might also break in the future :-/
Tried to implement something 'proper' using weakrefs, but I was not
understanding something there, so could not manage to make it work.
> Address memory leak when using until_any() with AsyncState.until_state()

- katcp/resource_client.py
- katcp/test/test_resource_client.py
@theunsa Please review carefully. I think there were some potential problems in the Container set_sensor_sampling and set_sensor_listener and I reworked both.
Also moved the two failing tests (test_set_sensor_sampling and test_set_sensor_listener) to the integrated container test class so that the test covers more and use less mocks.  Please also review the tests to see that it correctly test those two functions.
> Lize fix tests

- katcp/client.py
- katcp/core.py
- katcp/resource_client.py
If you receive a future that is already done (i.e. fut.done() == True) before yielding on itin a tornado coroutine, the yield statement will not result in a pass being made through the ioloop, effectively turning your coroutine into a blocking function. 
By timing for how long only 'done' futures are received one can adaptively force a trip through the ioloop by doing yield tornado.gen.moment when things have been blocking for too long.
> Improve latency in katcp client loops CB-568

- katcp/client.py
- katcp/server.py
At present we need to be able to send messages of 600K. We felt that we will double that and added some more then we get to a complicated number... so we said 2M.
> Changed the max message size from 128K to 2M.

- katcp/resource_client.py
1) Pylint pointed an indentation problem.
2) Check if the sensor exist before removing it.
This problem manifested itself on the stream service.
> Check that the sensor exists before removing it.

- Jenkinsfile
- katcp/core.py
- katcp/inspecting_client.py
- katcp/test/test_inspecting_client.py
- setup.cfg
Also minor dosctring, style and whitespace fixes
fixup inspecting_client test, remove setup.cfg
> Make InspectingClientAsync.connect() timeout match docstring

- katcp/inspecting_client.py
- katcp/test/test_sampling.py
Mostly this is documenting the model change objects using by
InspectingClientAsync. I also fixed up a few misc typos in comments and
log messages.
> Documentation improvements

- katcp/core.py
- katcp/inspecting_client.py
- katcp/resource_client.py
Also added some TODO comments with performance improvement ideas for
inspecting_client.py
> Docstring and style improvements

- katcp/test/test_testutils.py
- katcp/testutils.py
In the testutils module.
In support of implementing the async dev handler tests.
> Add a tornado AsyncWaitingMock complement to WaitingMock CB-1466

- CHANGELOG
- doc/releasenotes.rst
In preparation for the new 0.6.2 version.
> Added version 0.6.2 release notes

- katcp/core.py
- katcp/test/test_core.py
Also some minor pep8 fixes.
Added a simple test for a unicode message.
> Added error handling when parsing Message arguments and remove unicode characters from devices that do not only send ASCII (not following spec).

- katcp/server.py
- increase in Queue size to cater for more client connections. 
see [Jira MT-92](https://skaafrica.atlassian.net/browse/MT-92) for more info.
> increase MAX_QUEUE_SIZE to handle more clients

- Jenkinsfile
Port to new declarative syntax for Jenkins pipeline definitions in an attempting to fix our broken multibranch jobs because our new Jenkins agents inside containers don't have access to Docker daemon. this pull request is inline with a JIRA: [ MT-610](https://skaafrica.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=MT&modal=detail&selectedIssue=MT-610), for reference please check this PR: [141](https://github.com/ska-sa/katconf/pull/141)
> Ported Jenkins file script style to declarative style

- Jenkinsfile
Added `--user` so that we do not need root access in the test environment.
> Added --user to the Jenkinsfile

- Jenkinsfile
- Standardise the multibranch build job
> Trigger downstream publish artifacts job

- doc/how_to_contribute.rst
- doc/index.rst
A new release is planned, so adding some details on how to do it.
This is based on similar notes in https://github.com/tango-controls/pytango
> Add info on how to contribute

- CHANGELOG
- doc/conf.py
- doc/releasenotes.rst
Updates for pending release, and also fix an issue in the Sphinx build on readthedocs.
> Update changelog and release notes for v0.6.3

- katcp/client.py
- katcp/test/test_client.py
A number of `AsyncEvent` objects are created in the client's `__init__` method, resulting in them getting a reference to the current ioloop at the time of instantiation.  If a different ioloop is used when starting the client (which will happen in the "managed" case), this can cause problems.  E.g., if the original ioloop is closed before stopping the client, an exception occurs during
`yield self._stopped.until_set`.  This was only noticed after the changes in PR #206.
The fix is to recreate the `AsyncEvent` objects using the correct ioloop when starting the client.  Some of the other state variables that should have been cleared after stopping, for example the protocol received, are now also re-initialised each time.
Problems with `AsyncEvent` objects initialised in other higher level …
> Use correct ioloop for client AsyncEvent objects

- bench/benchserver.py
- bench/results.py
- bench/util.py
This PR fixes licensing related issues.
> Fix Licensing

- CHANGELOG.md
- doc/releasenotes.rst
- Added version information on changelog and release notes
This PR addresses issue #221
> Prepare for v0.7.0 release.

- Jenkinsfile
- pyproject.toml
- setup.cfg
This commit does the following:
- Added default setup.cfg (Refer to [CAM Developer's Guide](https://docs.google.com/document/d/1aZoIyR9tz5rCWr2qJKuMTmKp2IzHlFjrCFrpDDHFypM/edit#heading=h.whqqrvn0pw8f) which adds PEP8 strictness.)
- Added pyproject.toml config file which contains isort and black configurations/parameters.
- Added linting to static analysis stage on Jenkins
JIRA: [MT-1063](https://skaafrica.atlassian.net/browse/MT-1063)
> Automate code linting and reject PR if fails.

- CHANGELOG.md
Updated the CHANGELOG.md to reflect the PRs for the next release.
> Prepare for v0.7.1 release.

- CHANGELOG.md
This PR aligns the changelog with the upcoming release v0.7.2
> Align Changelog with upcoming release v0.7.2

- CHANGELOG.md
- doc/releasenotes.rst
Update `CHANGELOG.md` and `docs/releasenotes.rst` for new v0.8.0 release.
> Prepare for release v0.8.0

- CHANGELOG.md
- doc/releasenotes.rst
- katcp/kattypes.py
Update release notes and changelog for upcoming release of v0.9.2
> prepare v0.9.2
